load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//grain:__subpackages__"])

licenses(["notice"])

exports_files(glob(["*.array_record-*"]))

exports_files(glob(["*.tfrecord"]))
