licenses(["notice"])

py_binary(
    name = "load_from_gcsfuse",
    srcs = ["load_from_gcsfuse.py"],
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [
        "//grain",
        "@abseil-py//absl:app",
        "@abseil-py//absl/flags",
    ],
)
