version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  # Note this is set to false for now while the warnings are resolved
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
