# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grain/proto/execution_summary.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#grain/proto/execution_summary.proto\x12\x1egrain.python.execution_summary\"\xfd\x03\n\x10\x45xecutionSummary\x12J\n\x05nodes\x18\x01 \x03(\x0b\x32;.grain.python.execution_summary.ExecutionSummary.NodesEntry\x1a\xb7\x02\n\x04Node\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06inputs\x18\x04 \x03(\x05\x12\x17\n\x0fwait_time_ratio\x18\x05 \x01(\x01\x12 \n\x18total_processing_time_ns\x18\x06 \x01(\x03\x12\x1e\n\x16min_processing_time_ns\x18\x07 \x01(\x03\x12\x1e\n\x16max_processing_time_ns\x18\x08 \x01(\x03\x12\x1d\n\x15num_produced_elements\x18\t \x01(\x03\x12\x13\n\x0boutput_spec\x18\n \x01(\t\x12\x11\n\tis_output\x18\x0b \x01(\x08\x12\x13\n\x0bis_prefetch\x18\x0c \x01(\x08\x12\x16\n\x0e\x62ytes_consumed\x18\r \x01(\x03\x12\x16\n\x0e\x62ytes_produced\x18\x0e \x01(\x03\x1a\x63\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.grain.python.execution_summary.ExecutionSummary.Node:\x02\x38\x01\"c\n\x12\x45xecutionSummaries\x12M\n\x13\x65xecution_summaries\x18\x01 \x03(\x0b\x32\x30.grain.python.execution_summary.ExecutionSummaryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grain.proto.execution_summary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTIONSUMMARY_NODESENTRY']._options = None
  _globals['_EXECUTIONSUMMARY_NODESENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTIONSUMMARY']._serialized_start=72
  _globals['_EXECUTIONSUMMARY']._serialized_end=581
  _globals['_EXECUTIONSUMMARY_NODE']._serialized_start=169
  _globals['_EXECUTIONSUMMARY_NODE']._serialized_end=480
  _globals['_EXECUTIONSUMMARY_NODESENTRY']._serialized_start=482
  _globals['_EXECUTIONSUMMARY_NODESENTRY']._serialized_end=581
  _globals['_EXECUTIONSUMMARIES']._serialized_start=583
  _globals['_EXECUTIONSUMMARIES']._serialized_end=682
# @@protoc_insertion_point(module_scope)
