package(default_visibility = ["//grain:__subpackages__"])

licenses(["notice"])

py_library(
    name = "np_array_in_shared_memory",
    srcs = ["np_array_in_shared_memory.py"],
    srcs_version = "PY3",
    deps = ["//grain/_src/python:shared_memory_array"],
)
