package(default_visibility = ["//grain:__subpackages__"])

licenses(["notice"])

py_library(
    name = "device_put",
    srcs = ["device_put.py"],
    srcs_version = "PY3",
    deps = [
        "//grain/_src/python/dataset",
        "@pypi//numpy:pkg",
    ],
)
