load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//grain:__subpackages__"])

licenses(["notice"])

cc_library(
    name = "index_shuffle",
    srcs = ["index_shuffle.cc"],
    hdrs = ["index_shuffle.h"],
)
