load("@rules_python//python:pip.bzl", "compile_pip_requirements")

package(default_visibility = ["//grain:__subpackages__"])

licenses(["notice"])

cc_library(
    name = "index_shuffle",
    srcs = ["index_shuffle.cc"],
    hdrs = ["index_shuffle.h"],
)
